### PR TITLE
Promises

### PR DESCRIPTION
**Pull request by marcoscaceres**
Updated spec to use Promise instead of Future.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Sorry about the white space.. I'm running tidy on the next pull request as I'm currently fixing some issues with the markup.

**Comment by marcoscaceres** [comment]
Argh, I mean the line lengths, not the whitespace. Anyway, fixing now.

**Comment by zolkis** [comment]
ok, I wait a bit with merging

**Comment by marcoscaceres** [comment]
It's ok to merge this one. Then I'll send another PR (otherwise there will be merge conflict hell, I think).

**Pull request merged**
